"""
plot.py -- Reproduces paper Figures 4-8 from CSV data generated by main.go.

Usage:
    python plot.py                         # reads results_static.csv + results_dynamic.csv
    python plot.py --static my_static.csv  # custom CSV paths
    python plot.py --dynamic my_dyn.csv

Output files:
    fig4_8nodes.png   fig5_12nodes.png   fig6_16nodes.png   fig7_20nodes.png
    fig8_dynamic.png
    all_figures.png   (combined 3x2 grid, ready for the report)
"""

import argparse
import sys
import os
import shutil
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")          # headless -- works without a display
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from matplotlib.gridspec import GridSpec
from matplotlib.patches import Patch
from matplotlib.lines import Line2D

# -- Style constants -- colors extracted directly from the paper's Figs 4-7 -----
PBFT_BAR_COLOR  = "#2e6b2e"   # dark green  -- Throughput (PBFT)
OUR_BAR_COLOR   = "#a8d4ee"   # sky blue    -- Throughput (Our Protocol)
PBFT_LINE_COLOR = "#d62728"   # red         -- Latency (PBFT), square markers
OUR_LINE_COLOR  = "#f0a30a"   # orange      -- Latency (Our Protocol), circle markers
GRID_COLOR      = "#e5e7eb"
EDGE_COLOR      = "#888888"

FONT_FAMILY  = "DejaVu Sans"     # paper's charts use a sans-serif font
TITLE_SIZE   = 12
AXIS_SIZE    = 10
TICK_SIZE    = 9
LEGEND_SIZE  = 8.5
BAR_WIDTH    = 0.32
MARKER_SIZE  = 5
LINE_WIDTH   = 1.6
DPI          = 180


def set_paper_style():
    """Apply global matplotlib style that approximates IEEE paper figures."""
    plt.rcParams.update({
        "font.family":         FONT_FAMILY,
        "font.size":           AXIS_SIZE,
        "axes.titlesize":      TITLE_SIZE,
        "axes.labelsize":      AXIS_SIZE,
        "xtick.labelsize":     TICK_SIZE,
        "ytick.labelsize":     TICK_SIZE,
        "legend.fontsize":     LEGEND_SIZE,
        "axes.grid":           True,
        "grid.color":          GRID_COLOR,
        "grid.linewidth":      0.6,
        "axes.linewidth":      0.8,
        "axes.edgecolor":      EDGE_COLOR,
        "figure.facecolor":    "white",
        "savefig.bbox":        "tight",
        "savefig.dpi":         DPI,
    })


# ---------------------------------------------------------------------------------
# Core charting function -- matches Figures 4-7 dual-axis format
# ---------------------------------------------------------------------------------

def plot_static_figure(ax1, df_n, node_count, show_legend=True, title=None):
    """
    Draw one performance chart matching the paper's exact visual format:
    dark green / sky blue bars for throughput, red-square / orange-circle
    lines for latency, title printed inside the axes, split legend boxes
    (throughput top-left, latency top-right) exactly as in Figs 4-7.
    """
    loads = df_n["rps"].values
    x     = np.arange(len(loads))

    # -- Throughput bars (left axis) ----------------------------------------------
    ax1.bar(x - BAR_WIDTH/2, df_n["pbft_throughput"],
            BAR_WIDTH, color=PBFT_BAR_COLOR, label="Throughput (PBFT)",
            edgecolor="white", linewidth=0.4, zorder=3)
    ax1.bar(x + BAR_WIDTH/2, df_n["our_throughput"],
            BAR_WIDTH, color=OUR_BAR_COLOR, label="Throughput (Our Protocol)",
            edgecolor="white", linewidth=0.4, zorder=3)

    ax1.set_xlabel("Requests per second", fontsize=AXIS_SIZE)
    ax1.set_ylabel("Throughput (req/s)", fontsize=AXIS_SIZE, color="#1f3a93")
    ax1.set_xticks(x)
    ax1.set_xticklabels(loads, fontsize=TICK_SIZE)
    ax1.set_ylim(0, max(df_n["our_throughput"].max(), df_n["pbft_throughput"].max()) * 1.30)
    ax1.tick_params(axis="y", labelcolor="#1f3a93")
    ax1.yaxis.set_major_formatter(mtick.FormatStrFormatter("%.0f"))
    if title:
        ax1.set_title(title, fontsize=TITLE_SIZE, pad=8)

    # -- Latency lines (right axis), units = seconds, matching paper -------------
    ax2 = ax1.twinx()
    lat_pbft = df_n["pbft_latency_ms"] / 1000.0
    lat_ours = df_n["our_latency_ms"]  / 1000.0

    ax2.plot(x, lat_pbft, color=PBFT_LINE_COLOR,
             linewidth=LINE_WIDTH, linestyle="-",
             marker="s", markersize=MARKER_SIZE,
             label="Latency (PBFT)", zorder=4)
    ax2.plot(x, lat_ours, color=OUR_LINE_COLOR,
             linewidth=LINE_WIDTH, linestyle="-",
             marker="o", markersize=MARKER_SIZE,
             label="Latency (Our Protocol)", zorder=4)

    ax2.set_ylabel("Latency (s)", fontsize=AXIS_SIZE, color=PBFT_LINE_COLOR)
    lat_max = max(lat_pbft.max(), lat_ours.max())
    ax2.set_ylim(0, lat_max * 1.20)
    ax2.tick_params(axis="y", labelcolor=PBFT_LINE_COLOR)
    ax2.yaxis.set_major_formatter(mtick.FormatStrFormatter("%.2f"))

    # -- Split legend boxes, matching paper layout exactly -----------------------
    if show_legend:
        tp_handles = [
            Patch(color=PBFT_BAR_COLOR, label="Throughput (PBFT)"),
            Patch(color=OUR_BAR_COLOR,  label="Throughput (Our Protocol)"),
        ]
        lat_handles = [
            Line2D([0],[0], color=PBFT_LINE_COLOR, lw=LINE_WIDTH,
                   marker="s", ms=MARKER_SIZE, label="Latency (PBFT)"),
            Line2D([0],[0], color=OUR_LINE_COLOR, lw=LINE_WIDTH,
                   marker="o", ms=MARKER_SIZE, label="Latency (Our Protocol)"),
        ]
        ax1.legend(handles=tp_handles, loc="upper left",
                   fontsize=LEGEND_SIZE, framealpha=0.95,
                   edgecolor=EDGE_COLOR, handlelength=1.4)
        ax2.legend(handles=lat_handles, loc="upper right",
                   fontsize=LEGEND_SIZE, framealpha=0.95,
                   edgecolor=EDGE_COLOR, handlelength=1.4)

    return ax2


# ---------------------------------------------------------------------------------
# Figures 4-7: individual files + combined grid
# ---------------------------------------------------------------------------------

def generate_static_figures(df):
    """Generate Fig 4-7: one chart per node count, plus a combined 2x2 grid."""

    node_configs = [
        (8,  "Performance Comparison for 8 Nodes"),
        (12, "Performance Comparison for 12 Nodes"),
        (16, "Performance Comparison for 16 Nodes"),
        (20, "Performance Comparison for 20 Nodes"),
    ]
    captions = [
        "Fig. 4 -- 8 nodes (n=4, m=2)",
        "Fig. 5 -- 12 nodes (n=4, m=3)",
        "Fig. 6 -- 16 nodes (n=4, m=4)",
        "Fig. 7 -- 20 nodes (n=4, m=5)",
    ]
    fig_filenames = ["fig4_8nodes.png", "fig5_12nodes.png",
                     "fig6_16nodes.png", "fig7_20nodes.png"]

    # -- Individual figures -------------------------------------------------------
    for (n_count, chart_title), caption, fname in zip(node_configs, captions, fig_filenames):
        df_n = df[df["nodes"] == n_count].copy()
        if df_n.empty:
            print(f"  SKIP  No data for nodes={n_count}, skipping {fname}")
            continue

        fig, ax1 = plt.subplots(figsize=(6.0, 4.2))
        plot_static_figure(ax1, df_n, n_count, show_legend=True, title=chart_title)
        fig.text(0.5, -0.02, caption, ha="center", fontsize=9, style="italic")
        fig.tight_layout()
        fig.savefig(fname, bbox_inches="tight")
        plt.close(fig)
        print(f"  OK  Saved {fname}")

    # -- Combined 2x2 grid (all_figures.png) -------------------------------------
    fig, axes = plt.subplots(2, 2, figsize=(13, 9))
    fig.suptitle(
        "Performance Comparison: Our Protocol vs Classic PBFT\n"
        "(reproduced from our Go implementation -- same chart format as paper Figs 4-7)",
        fontsize=12, fontweight="bold", y=1.02
    )

    for idx, ((n_count, chart_title), ax1) in enumerate(
            zip(node_configs, axes.flatten())):
        df_n = df[df["nodes"] == n_count].copy()
        if df_n.empty:
            ax1.set_visible(False)
            continue
        plot_static_figure(ax1, df_n, n_count, show_legend=True, title=chart_title)

    fig.tight_layout()
    fig.savefig("all_figures.png", bbox_inches="tight")
    plt.close(fig)
    print("  OK  Saved all_figures.png (combined 2x2 grid)")


# ---------------------------------------------------------------------------------
# Figure 8: dynamic testbed -- matches paper exactly
# Format: grouped bar chart (throughput) + solid lines (latency) per tick rate
# ---------------------------------------------------------------------------------

def generate_dynamic_figure(df_dyn):
    """
    Generate Fig 8: Throughput and Latency vs Number of Nodes (Dynamic Testbed).

    Visual format matches the paper Figure 8 exactly:
      - X-axis: number of nodes (8, 12, 16, 20)
      - Left Y-axis: Throughput (req/s) -- grouped bar chart, one bar per tick rate
      - Right Y-axis: Latency (s) -- solid lines with circle markers, one per tick rate
      - Colours: gold / orange-red / crimson / magenta / cyan  (5 tick rates)
      - Two separate legends: throughput bars (top-right), latency lines (lower-right)
      - Title: "Throughput and Latency vs Number of Nodes"
      - Dashed grid lines
    """
    tick_rates = sorted(df_dyn["tick_rate_s"].unique())   # [10, 20, 30, 40, 50]
    node_vals  = sorted(df_dyn["nodes"].unique())          # [8, 12, 16, 20]
    n_ticks    = len(tick_rates)
    n_nodes    = len(node_vals)

    # Colours matching the paper Figure 8: gold, orange-red, crimson, magenta, cyan
    colors = ["#FFA500", "#FF4500", "#DC143C", "#FF69B4", "#00BFFF"]

    fig, ax1 = plt.subplots(figsize=(8.0, 5.5))
    ax2 = ax1.twinx()

    # -- Bar chart: throughput grouped by node count -----------------------------
    total_width = 0.75              # width of all bars in one group
    bar_w       = total_width / n_ticks
    x_centers   = np.arange(n_nodes)   # one group per node count

    for i, tick in enumerate(tick_rates):
        df_t = df_dyn[df_dyn["tick_rate_s"] == tick].sort_values("nodes")
        tp_vals = []
        for n in node_vals:
            row = df_t[df_t["nodes"] == n]
            tp_vals.append(float(row["throughput"].values[0]) if len(row) else 0.0)
        bar_offsets = x_centers - total_width / 2.0 + bar_w * (i + 0.5)
        ax1.bar(bar_offsets, tp_vals, bar_w,
                color=colors[i], alpha=0.85,
                label=f"Tick Rate {tick}s", zorder=2)

    # -- Line chart: latency on right axis (solid lines) -------------------------
    for i, tick in enumerate(tick_rates):
        df_t = df_dyn[df_dyn["tick_rate_s"] == tick].sort_values("nodes")
        lat_s = []
        for n in node_vals:
            row = df_t[df_t["nodes"] == n]
            lat_s.append(float(row["latency_ms"].values[0]) / 1000.0 if len(row) else 0.0)
        ax2.plot(x_centers, lat_s,
                 color=colors[i], linewidth=LINE_WIDTH + 0.6, linestyle="-",
                 marker="o", markersize=MARKER_SIZE + 1,
                 label=f"Tick Rate {tick}s", zorder=5)

    # -- Axes labels & ticks -----------------------------------------------------
    ax1.set_xlabel("Number of Nodes (Dynamically Growing)", fontsize=AXIS_SIZE)
    ax1.set_ylabel("Throughput (req/s)", fontsize=AXIS_SIZE)
    ax2.set_ylabel("Latency (s)", fontsize=AXIS_SIZE)

    ax1.set_xticks(x_centers)
    ax1.set_xticklabels([str(n) for n in node_vals], fontsize=TICK_SIZE)

    tp_max = df_dyn["throughput"].max()
    ax1.set_ylim(0, tp_max * 1.50)

    lat_s_all = df_dyn["latency_ms"] / 1000.0
    lat_min   = lat_s_all.min()
    lat_max   = lat_s_all.max()
    # Give some padding below the min so lines don't sit on the axis
    ax2.set_ylim(max(0, lat_min * 0.75), lat_max * 1.15)
    ax2.yaxis.set_major_formatter(mtick.FormatStrFormatter("%.2f"))

    # -- Dashed grid lines (paper style) -----------------------------------------
    ax1.set_axisbelow(True)
    ax1.xaxis.grid(True, linestyle="--", linewidth=0.8, color="#cccccc")
    ax1.yaxis.grid(True, linestyle="--", linewidth=0.8, color="#cccccc")
    # Disable the default rcParams grid that would conflict
    ax1.grid(True, linestyle="--", linewidth=0.8, color="#cccccc")

    # -- Title -------------------------------------------------------------------
    ax1.set_title("Throughput and Latency vs Number of Nodes",
                  fontsize=TITLE_SIZE + 1, fontweight="bold", pad=10)

    # -- Two separate legends matching paper layout ------------------------------
    # Top-right: throughput bars
    bar_handles = [Patch(color=colors[i], alpha=0.85, label=f"Tick Rate {t}s")
                   for i, t in enumerate(tick_rates)]
    leg_bars = ax1.legend(handles=bar_handles,
                          loc="upper right",
                          fontsize=LEGEND_SIZE,
                          title="Tick Rate", title_fontsize=LEGEND_SIZE,
                          framealpha=0.85, edgecolor="#aaaaaa")

    # Lower-right: latency lines
    line_handles = [Line2D([0], [0], color=colors[i], lw=LINE_WIDTH + 0.6,
                           marker="o", ms=MARKER_SIZE + 1,
                           label=f"Tick Rate {t}s")
                    for i, t in enumerate(tick_rates)]
    ax2.legend(handles=line_handles,
               loc="lower right",
               fontsize=LEGEND_SIZE,
               title="Tick Rate", title_fontsize=LEGEND_SIZE,
               framealpha=0.85, edgecolor="#aaaaaa")

    ax1.add_artist(leg_bars)   # keep bar legend after ax2 legend is drawn

    fig.tight_layout()
    fig.savefig("fig8_dynamic.png")
    # Copy to assets folder
    try:
        shutil.copy("fig8_dynamic.png", "assets/fig8_dynamic.png")
    except Exception:
        pass
    plt.close(fig)
    print("  OK  Saved fig8_dynamic.png")


# ---------------------------------------------------------------------------------
# Bonus: complexity reduction chart
# ---------------------------------------------------------------------------------

def generate_complexity_chart():
    """Bar chart showing message count: Our O(n^1.5) vs PBFT O(n^2)."""
    ps = np.array([8, 12, 16, 20, 32, 64, 100])
    our  = np.power(ps, 1.5)
    pbft = ps ** 2

    fig, ax = plt.subplots(figsize=(6, 3.6))
    x = np.arange(len(ps))
    ax.bar(x - BAR_WIDTH/2, pbft, BAR_WIDTH,
           color=PBFT_BAR_COLOR, label="PBFT O(n2)", edgecolor="white")
    ax.bar(x + BAR_WIDTH/2, our,  BAR_WIDTH,
           color=OUR_BAR_COLOR,  label="Our Protocol O(n^1.5)", edgecolor="white")
    ax.set_xticks(x)
    ax.set_xticklabels([str(p) for p in ps])
    ax.set_xlabel("Total Nodes (p)", fontsize=AXIS_SIZE)
    ax.set_ylabel("Message Count", fontsize=AXIS_SIZE)
    ax.set_title("Message Complexity: Our Protocol vs Classic PBFT\n"
                 "(Table II/III -- Paper Section XIII)",
                 fontsize=TITLE_SIZE, pad=6)
    ax.legend(fontsize=LEGEND_SIZE, framealpha=0.9)
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(
        lambda x, _: f"{int(x):,}"))

    # Add speedup labels on top
    for i, (o, p_) in enumerate(zip(our, pbft)):
        ax.text(x[i], p_ + p_*0.03, f"{p_/o:.1f}x",
                ha="center", va="bottom", fontsize=7, color=PBFT_BAR_COLOR,
                fontweight="bold")

    fig.tight_layout()
    fig.savefig("fig_complexity.png")
    plt.close(fig)
    print("  OK  Saved fig_complexity.png")


# ---------------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Plot paper figures from simulation CSVs")
    ap.add_argument("--static",  default="results_static.csv",
                    help="Static testbed CSV (default: results_static.csv)")
    ap.add_argument("--dynamic", default="results_dynamic.csv",
                    help="Dynamic testbed CSV (default: results_dynamic.csv)")
    args = ap.parse_args()

    set_paper_style()

    print("\n=== Vehicular BFT -- Figure Generator ==============================")

    # -- Load static data -------------------------------------------------------
    if not os.path.exists(args.static):
        print(f"  ERROR: {args.static} not found.")
        print("  Run:  go run main.go -paper-eval  (to generate CSV first)")
        sys.exit(1)

    df_static = pd.read_csv(args.static)
    required_static = {"nodes","rps","our_throughput","our_latency_ms",
                       "pbft_throughput","pbft_latency_ms"}
    if not required_static.issubset(df_static.columns):
        print(f"  ERROR: {args.static} missing columns: "
              f"{required_static - set(df_static.columns)}")
        sys.exit(1)
    print(f"\n  Loaded {args.static}: {len(df_static)} rows, "
          f"nodes={sorted(df_static['nodes'].unique())}, "
          f"rps={sorted(df_static['rps'].unique())}")

    # -- Load dynamic data -------------------------------------------------------
    df_dynamic = None
    if os.path.exists(args.dynamic):
        df_dynamic = pd.read_csv(args.dynamic)
        print(f"  Loaded {args.dynamic}: {len(df_dynamic)} rows, "
              f"tick_rates={sorted(df_dynamic['tick_rate_s'].unique())}")
    else:
        print(f"  WARNING: {args.dynamic} not found -- skipping Fig 8")

    print()

    # -- Generate figures -------------------------------------------------------
    generate_static_figures(df_static)

    if df_dynamic is not None:
        generate_dynamic_figure(df_dynamic)

    generate_complexity_chart()

    print("\n=== Summary of generated files =====================================")
    expected = ["fig4_8nodes.png","fig5_12nodes.png","fig6_16nodes.png",
                "fig7_20nodes.png","fig8_dynamic.png","fig_complexity.png",
                "all_figures.png"]
    for f in expected:
        status = "OK" if os.path.exists(f) else "MISSING"
        print(f"  {status}  {f}")

    print("\n  To regenerate with fresh simulation data:")
    print("    go run main.go -paper-eval")
    print("  To plot from existing CSVs only:")
    print("    python plot.py")
    print()


if __name__ == "__main__":
    main()